language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ngbp-typescript' ]; then cd .. && eval "mv $currentfolder generator-ngbp-typescript" && cd generator-ngbp-typescript; fi

